#!/bin/sh
#
# Bootstrap development of mpeg4ip with GNU autoconf, automake, and libtool
# Assumes tools are available on the system
#

# Check that we can find libtool
# Frequently it hasn't been installed
if glibtool --version > /dev/null 2> /dev/null
then 
    libtool=glibtool
    if libtoolize --version > /dev/null
    then
	echo "Found link for libtoolize"
    else 
	echo "Need a link for libtoolize to glibtoolize"
	echo "Please see readme for how to make on OS X"
	exit 1
    fi
elif libtool --version >/dev/null
then libtool=libtool
else echo "libtool does not appear to be installed."
     echo "Please install it and then rerun this script."
     exit 1
fi

if (test ! -f ./configure) || (test ! -f ./lib/SDL/configure)
then echo "Please run cvs_bootstrap instead."
     echo "Please note that you will need autoconf, automake and libtool"
     echo "of the correct version as specified in the README"
     exit 1
fi

set -x

# if src tree is created via cvs export to tar.gz
# then empty directories in the repository are pruned
# this code recreates the empty directories
# if src tree is checked out directly via cvs, this is a no-op
mkdir -p ./config || exit 1

pwd=`pwd`
for	dir \
in	$pwd/lib/SDL $pwd
do	cd $dir
	./configure "$@" || exit 1
done
set +x

# Now ready to run make
echo "ready to make"
