#ifndef __PROFILE_VIDEO__
#define __PROFILE_VIDEO__ 1
#include "profile_list.h"
#include "mp4.h"

#define VIDEO_ENCODER_XVID "xvid"
#define VIDEO_ENCODING_MPEG4 "MPEG4"

#define VIDEO_NTSC_FRAME_RATE	((float)29.97)
#define VIDEO_PAL_FRAME_RATE	((float)25.00)

DECLARE_CONFIG(CONFIG_VIDEO_PROFILE_NAME);
DECLARE_CONFIG(CONFIG_VIDEO_ENCODER);
DECLARE_CONFIG(CONFIG_VIDEO_ENCODING);
DECLARE_CONFIG(CONFIG_VIDEO_WIDTH);
DECLARE_CONFIG(CONFIG_VIDEO_HEIGHT);
DECLARE_CONFIG(CONFIG_VIDEO_FRAME_RATE);
DECLARE_CONFIG(CONFIG_VIDEO_KEY_FRAME_INTERVAL);
DECLARE_CONFIG(CONFIG_VIDEO_BIT_RATE);
DECLARE_CONFIG(CONFIG_VIDEO_FORCE_PROFILE_ID);
DECLARE_CONFIG(CONFIG_VIDEO_PROFILE_ID);
DECLARE_CONFIG(CONFIG_VIDEO_TIMEBITS);
DECLARE_CONFIG(CONFIG_VIDEO_H261_QUALITY);
DECLARE_CONFIG(CONFIG_VIDEO_H261_QUALITY_ADJ_FRAMES);
DECLARE_CONFIG(CONFIG_VIDEO_MPEG4_PAR_WIDTH);
DECLARE_CONFIG(CONFIG_VIDEO_MPEG4_PAR_HEIGHT);
DECLARE_CONFIG(CONFIG_XVID10_VIDEO_QUALITY);
DECLARE_CONFIG(CONFIG_XVID10_USE_GMC);
DECLARE_CONFIG(CONFIG_XVID10_USE_QPEL);
DECLARE_CONFIG(CONFIG_XVID10_USE_LUMIMASK);
DECLARE_CONFIG(CONFIG_XVID10_USE_INTERLACING);

#ifdef DECLARE_CONFIG_VARIABLES
static SConfigVariable VideoProfileConfigVariables[] = {
  CONFIG_STRING(CONFIG_VIDEO_PROFILE_NAME, "profileName", NULL),
  CONFIG_STRING(CONFIG_VIDEO_ENCODER, "videoEncoder", VIDEO_ENCODER_XVID),
  CONFIG_STRING(CONFIG_VIDEO_ENCODING, "videoEncoding", VIDEO_ENCODING_MPEG4),

  CONFIG_INT(CONFIG_VIDEO_WIDTH, "videoWidth", 320),
  CONFIG_INT(CONFIG_VIDEO_HEIGHT, "videoHeight", 240),
  CONFIG_FLOAT(CONFIG_VIDEO_FRAME_RATE, "videoFrameRate", 
	       VIDEO_NTSC_FRAME_RATE),
  CONFIG_FLOAT(CONFIG_VIDEO_KEY_FRAME_INTERVAL, "videoKeyFrameInterval", 
	       2.0),

  CONFIG_INT(CONFIG_VIDEO_BIT_RATE, "videoBitRate",500),
  CONFIG_BOOL(CONFIG_VIDEO_FORCE_PROFILE_ID, "videoForceProfileId", false),
  CONFIG_INT(CONFIG_VIDEO_PROFILE_ID, "videoProfileId",MPEG4_SP_L3),
  CONFIG_INT(CONFIG_VIDEO_TIMEBITS, "videoTimebits", 0),
  CONFIG_INT(CONFIG_VIDEO_H261_QUALITY, "videoH261Quality", 10),
  CONFIG_INT(CONFIG_VIDEO_H261_QUALITY_ADJ_FRAMES, "videoH261QualityAdjFrames", 8),
  CONFIG_INT(CONFIG_VIDEO_MPEG4_PAR_WIDTH, "videoMpeg4ParWidth", 0),
  CONFIG_INT(CONFIG_VIDEO_MPEG4_PAR_HEIGHT, "videoMpeg4ParHeight", 0),

  CONFIG_INT(CONFIG_XVID10_VIDEO_QUALITY, "xvid10VideoQuality", 6),
  CONFIG_BOOL(CONFIG_XVID10_USE_GMC, "xvid10UseGmc", false),
  CONFIG_BOOL(CONFIG_XVID10_USE_QPEL, "xvid10UseQpel", false),
  CONFIG_BOOL(CONFIG_XVID10_USE_LUMIMASK, "xvid10UseLumimask", false),
  CONFIG_BOOL(CONFIG_XVID10_USE_INTERLACING, "xvid10UseInterlacing", false),
};
#endif

class CVideoProfile : public CProfileList
{
  public:
  CVideoProfile(const char *directory) :
    CProfileList(directory, "video") {
  };

  ~CVideoProfile(void) {
  };
  
 protected:
  void LoadConfigVariables(CProfileEntry *e);
};

#endif
