.TH "SDL_EnableKeyRepeat" "3" "Thu 12 Oct 2000, 13:51" "SDL" "SDL API Reference" 
.SH "NAME"
SDL_EnableKeyRepeat\- Set keyboard repeat rate\&.
.SH "SYNOPSIS"
.PP
\fB#include "SDL\&.h"
.sp
\fBint \fBSDL_EnableKeyRepeat\fP\fR(\fBint delay, int interval\fR);
.SH "DESCRIPTION"
.PP
Enables or disables the keyboard repeat rate\&.
.PP
Setting \fBdelay\fR to 0 disables key repeating completely\&. Good default values are \fBSDL_DEFAULT_REPEAT_DELAY\fP and \fISDL_DEFAULT_REPEAT_INTERVAL\fP\&.
.SH "RETURN VALUE"
.PP
Returns \fB0\fR on success and \fB-1\fR on failure\&.
...\" created by instant / docbook-to-man, Thu 12 Oct 2000, 13:51
