.TH "SDL_ThreadID" "3" "Thu 12 Oct 2000, 13:50" "SDL" "SDL API Reference" 
.SH "NAME"
SDL_ThreadID\- Get the 32-bit thread identifier for the current thread\&.
.SH "SYNOPSIS"
.PP
\fB#include "SDL\&.h"
#include "SDL_thread\&.h"
.sp
\fBUint32 \fBSDL_ThreadID\fP\fR(\fBvoid\fR)
.SH "DESCRIPTION"
.PP
Get the 32-bit thread identifier for the current thread\&.
...\" created by instant / docbook-to-man, Thu 12 Oct 2000, 13:50
