.TH "SDL_ShowCursor" "3" "Thu 12 Oct 2000, 13:50" "SDL" "SDL API Reference" 
.SH "NAME"
SDL_ShowCursor\- Toggle whether or not the cursor is shown on the screen\&.
.SH "SYNOPSIS"
.PP
\fB#include "SDL\&.h"
.sp
\fBint \fBSDL_ShowCursor\fP\fR(\fBint toggle\fR);
.SH "DESCRIPTION"
.PP
Toggle whether or not the cursor is shown on the screen\&.
.PP
The cursor starts off displayed, but can be turned off\&.
.SH "RETURN VALUE"
.PP
\fBSDL_ShowCursor\fP returns \fB1\fR if the cursor was being displayed before the call, or \fB0\fR if it was not\&.
.SH "SEE ALSO"
.PP
\fI\fBSDL_CreateCursor\fP\fR, \fI\fBSDL_SetCursor\fP\fR
...\" created by instant / docbook-to-man, Thu 12 Oct 2000, 13:50
