.TH "SDL_GetCursor" "3" "Thu 12 Oct 2000, 13:50" "SDL" "SDL API Reference" 
.SH "NAME"
SDL_GetCursor\- Get the currently active mouse cursor\&.
.SH "SYNOPSIS"
.PP
\fB#include "SDL\&.h"
.sp
\fBSDL_Cursor *\fBSDL_GetCursor\fP\fR(\fBvoid\fR);
.SH "DESCRIPTION"
.PP
Returns the currently active mouse cursor\&.
.SH "SEE ALSO"
.PP
\fI\fBSDL_SetCursor\fP\fR, \fI\fBSDL_CreateCursor\fP\fR, \fI\fBSDL_ShowCursor\fP\fR
...\" created by instant / docbook-to-man, Thu 12 Oct 2000, 13:50
