#!/bin/bash
# mp4encode <file-prefix>

# Initialize default values for options
let videoWidth=320
let videoHeight=240
let bitRate=500

# For Divx encoder, this generates 1 I frame every second (the rest being P's)
let ifrequency=30
# For ISO encoder, these default values yield I P B B P B B ... for every 1 second
let pfrequency=9
let bfrequency=2
let fps=30

let use_divx=0

# Process any command line options
while getopts "b:B:dh:I:P:r:w:" opt; do
	case $opt in
		b ) let bitrate=$OPTARG ;;
		B ) let bfrequency=$OPTARG ;;
		d ) let use_divx=1 ;;
		h ) let videoHeight=$OPTARG ;;
		I ) let ifrequency=$OPTARG ;;
		P ) let pfrequency=$OPTARG ;;
		r ) let fps=$OPTARG ;;
		w ) let videoWidth=$OPTARG ;;
		\? ) echo "usage: $0 [-b bframe_frequency] [-d] [-h height] [-r rate] [-w width] file_prefix"
			exit 1 ;;
	esac
done
shift $(($OPTIND - 1))

# Some more initialization
prefix=$1
let rawframesize=(${videoWidth}*${videoHeight}*3)/2
here=`pwd`

set -o xtrace

# Create output directories for video encoder if necessary
if [ $use_divx = 0 ]; then 
	if [ ! -d mp4vout ]; then
		mkdir mp4vout
	fi
	if [ ! -d yuvout ]; then
		mkdir yuvout
	fi
fi

date
echo "Starting encode of $prefix"

if [ ! -f $prefix.yuv ] || [ $prefix.avi -nt $prefix.yuv ]; then
	echo "Splitting out video from avi"
	avi2raw -v $prefix.avi $prefix.yuv
fi

numbytes=`wc -c ${prefix}.yuv | sed -e "s/${prefix}.yuv//"`
let numframes=$((${numbytes}/${rawframesize}))
let lastframe=${numframes}-1

date
echo "Encoding ${numframes} frames of video"

if [ $use_divx = 1 ]; then 
	divxenc -b ${bitRate} -h ${videoHeight} -w ${videoWidth} -r ${fps} -i ${ifrequency} ${prefix}.yuv ${prefix}.divx
else
# Create video encoder parameters file from template
	sed -e "s?BASEDIR?${here}?" -e "s/FILEPREFIX/${prefix}/" -e "s/LASTFRAME/${lastframe}/" -e "s/FRAMEWIDTH/${videoWidth}/" -e "s/FRAMEHEIGHT/${videoHeight}/" -e "s/FRAMERATE/${fps}/" -e "s/BFREQUENCY/${bfrequency}/" -e "s/PFREQUENCY/${pfrequency}/" template.par > ${prefix}.par 

	mp4venc ${prefix}.par
	mv ./mp4vout/01/${prefix}.cmp ./${prefix}.mp4v
	rm ./yuvout/01/${prefix}.yuv
fi

date
if [ ! -f $prefix.pcm ] || [ $prefix.avi -nt $prefix.pcm ]; then
	echo "Splitting out audio from avi"
	avi2raw -a ${prefix}.avi ${prefix}.pcm
fi

date
echo "Encoding audio"
faac -r -pLOW -b64 ${prefix}.pcm

date
rm -f ${prefix}.mp4

echo "Packetizing video"
if [ $use_divx -eq 1 ]; then
	mp4vpkt -t -d -height=${videoHeight} -width=${videoWidth} -rate=${fps} -profile="simple@L3" ${prefix}.divx ${prefix}.mp4 > ${prefix}_vpkt.out
else
	mp4vpkt -t -d -bfrequency=${bfrequency} -height=${videoHeight} -width=${videoWidth} -rate=${fps} -profile="main@L2" ${prefix}.mp4v ${prefix}.mp4 > ${prefix}_vpkt.out
fi

echo "Packetizing audio with video"
mp4apkt -t -d -merge ${prefix}.aac ${prefix}.mp4 > ${prefix}_avpkt.out

set +o xtrace

date
echo "Finished, results are in $prefix.mp4"

# Print some interesting statistics
if [ $use_divx -eq 1 ]; then
	numbytes=`wc -c ${prefix}.divx | sed -e "s/${prefix}.divx//"` 
else
	numbytes=`wc -c ${prefix}.mp4v | sed -e "s/${prefix}.mp4v//"` 
fi
let videoRate="((${numbytes} / ${numframes}) * ${fps} * 8) / 1000"

numbytes=`wc -c ${prefix}.aac | sed -e "s/${prefix}.aac//"` 
let audioRate="((${numbytes} / ${numframes}) * ${fps} * 8) / 1000"

let totalRate="${videoRate} + ${audioRate}"

echo "Compressed video ${videoRate} Kbps"
echo "Compressed audio ${audioRate} Kbps"
echo "Compressed total ${totalRate} Kbps"
