#!/bin/bash
# mp4encode <file-prefix>

# Initialize default values for options
let bfrequency=2
let videoWidth=320
let videoHeight=240
let fps=30

# Process any command line options
while getopts "b:h:r:w:" opt; do
	case $opt in
		b ) let bfrequency=$OPTARG ;;
		h ) let videoHeight=$OPTARG ;;
		r ) let fps=$OPTARG ;;
		w ) let videoWidth=$OPTARG ;;
		\? ) echo "usage: $0 [-b bframe_frequency] [-h height] [-r rate] [-w width] file_prefix"
			exit 1 ;;
	esac
done
shift $(($OPTIND - 1))

# Some more initialization
prefix=$1
let rawframesize=(${videoWidth}*${videoHeight}*3)/2
here=`pwd`

set -o xtrace

# Create output directories for video encoder if necessary
if [ ! -d mp4vout ]; then
	mkdir mp4vout
fi

if [ ! -d yuvout ]; then
	mkdir yuvout
fi

date
echo "Starting encode of $prefix"

if [ ! -f $prefix.yuv ] || [ $prefix.avi -nt $prefix.yuv ]; then
	echo "Splitting out video from avi"
	avi2raw -v $prefix.avi $prefix.yuv
fi

# Create video encoder parameters file from template
numbytes=`wc -c ${prefix}.yuv | sed -e "s/${prefix}.yuv//"`
let numframes=$((${numbytes}/${rawframesize}))
let lastframe=${numframes}-1
sed -e "s?BASEDIR?${here}?" -e "s/FILEPREFIX/${prefix}/" -e "s/LASTFRAME/${lastframe}/" -e "s/FRAMEWIDTH/${videoWidth}/" -e "s/FRAMEHEIGHT/${videoHeight}/" -e "s/FRAMERATE/${fps}/" -e "s/BFREQUENCY/${bfrequency}/" template.par > ${prefix}.par 

date
echo "Encoding ${numframes} frames of video"
mp4venc ${prefix}.par
mv ./mp4vout/01/${prefix}.cmp ./${prefix}.mp4v
rm ./yuvout/01/${prefix}.yuv

date
if [ ! -f $prefix.pcm ] || [ $prefix.avi -nt $prefix.pcm ]; then
	echo "Splitting out audio from avi"
	avi2raw -a ${prefix}.avi ${prefix}.pcm
fi

date
echo "Encoding audio"
faac -r -pLOW -b64 ${prefix}.pcm

date
rm -f ${prefix}.mov

echo "Packetizing video"
mp4vpkt -t -d -bfrequency=${bfrequency} -height=${videoHeight} -width=${videoWidth} -rate=${fps} ${prefix}.mp4v ${prefix}.mov > ${prefix}_vpkt.out

echo "Packetizing audio with video"
mp4apkt -t -d -merge ${prefix}.aac ${prefix}.mov > ${prefix}_avpkt.out

set +o xtrace

date
echo "Finished, results are in $prefix.mov"

# Print some interesting statistics
numbytes=`wc -c ${prefix}.mp4v | sed -e "s/${prefix}.mp4v//"` 
let videoRate="((${numbytes} / ${numframes}) * ${fps} * 8) / 1000"

numbytes=`wc -c ${prefix}.aac | sed -e "s/${prefix}.aac//"` 
let audioRate="((${numbytes} / ${numframes}) * ${fps} * 8) / 1000"

let totalRate="${videoRate} + ${audioRate}"

echo "Compressed video ${videoRate} Kbps"
echo "Compressed audio ${audioRate} Kbps"
echo "Compressed total ${totalRate} Kbps"
