#!/bin/sh

#Darwin BuildTarball script

PLAT=`uname`

echo removing DarwinStreamingSrvr3-$PLAT.tar.gz
if rm -f DarwinStreamingSrvr3-$PLAT.tar.gz; 
then :
fi

echo removing DarwinStreamingSrvr3-$PLAT
if rm -rf DarwinStreamingSrvr3-$PLAT; 
then :
fi

#cvs -q up
./Buildit clean
./Buildit
./DSS_MakeRoot -f DarwinStreamingSrvr3-$PLAT
tar cvf DarwinStreamingSrvr3-$PLAT.tar DarwinStreamingSrvr3-$PLAT
gzip DarwinStreamingSrvr3-$PLAT.tar

./DSS_MakeProxyRoot StreamingProxy-3.0-$PLAT
tar cvf StreamingProxy-3.0-$PLAT.tar StreamingProxy-3.0-$PLAT
gzip StreamingProxy-3.0-$PLAT.tar

echo Done!
