#!/bin/sh

#Darwin BuildTarball script

PLAT=`uname`

echo removing StreamingProxy-3.0-MacOSX.tar.gz
if rm -f StreamingProxy-3.0-MacOSX.tar.gz; 
then :
fi

echo removing StreamingProxy-3.0-MacOSX
if rm -rf StreamingProxy-3.0-MacOSX; 
then :
fi

#cvs -q up
make
cp StreamingProxy StreamingProxy.tproj/

./DSS_MakeProxyRoot StreamingProxy-3.0-MacOSX
tar cvf StreamingProxy-3.0-MacOSX.tar StreamingProxy-3.0-MacOSX
gzip StreamingProxy-3.0-MacOSX.tar

echo Done!
