#!/bin/sh

# Install script for the Darwin Streaming Server
# source release


echo;echo Installing Darwin Streaming Server;echo

if [ `uname` != "SunOS" ]; then
	USERID=`id -u`
else
	USERID=`/usr/xpg4/bin/id -u`
fi

if [ $USERID = 0 ]; then

	echo Removing previous versions of Darwin Streaming Server
	if [ -f /usr/sbin/DarwinStreamingServer ]; then
		echo removing /usr/sbin/DarwinStreamingServer
		rm -f /usr/sbin/DarwinStreamingServer 
	fi
	
	if [ -f /usr/sbin/PlaylistBroadcaster ]; then
		echo removing /usr/sbin/PlaylistBroadcaster
		rm -f /usr/sbin/PlaylistBroadcaster
	fi
	
	if [ -f /usr/sbin/qtpasswd ]; then
		echo removing /usr/sbin/qtpasswd
		rm -f /usr/sbin/qtpasswd
	fi

	if [ -d /usr/sbin/StreamingServerModules ]; then
		echo removing /usr/sbin/StreamingServerModules
		rm -rf /usr/sbin/StreamingServerModules
	fi
	
	if [ -f /usr/local/bin/streamingadminserver.pl ]; then
		echo removing /usr/local/bin/streamingadminserver.pl
		rm -f /usr/local/bin/streamingadminserver.pl
	fi

	if [ -f /usr/local/sbin/SpamPro ]; then
		echo removing /usr/local/sbin/SpamPro
		rm -f /usr/local/sbin/SpamPro
	fi

	echo

	echo copying "DarwinStreamingServer" to "/usr/local/sbin/DarwinStreamingServer"
	if [ ! -d /usr/local/sbin ]; then
		echo creating "/usr/local/sbin" directory
		mkdir -p /usr/local/sbin
	fi
	cp -f DarwinStreamingServer /usr/local/sbin/
	
	
	echo copying "PlaylistBroadcaster" to "/usr/local/bin/PlaylistBroadcaster"
	cp -f PlaylistBroadcaster /usr/local/bin/
	
	echo copying "qtpasswd" to "/usr/local/bin/qtpasswd"
	cp -f qtpasswd /usr/local/bin/

	# For now, do not copy modules as there are no supported dynamic modules
	# echo copying modules to "/usr/local/sbin/StreamingServerModules"
	if [ ! -d /usr/local/sbin/StreamingServerModules ]; then
		echo creating "/usr/local/sbin/StreamingServerModules" directory
		mkdir /usr/local/sbin/StreamingServerModules
	fi
	# cp -f StreamingServerModules/* /usr/local/sbin/StreamingServerModules/
	
	if [ ! -d /etc/streaming ]; then
		echo creating "/etc/streaming" directory
		mkdir -p /etc/streaming
	fi
	
	echo copying "streamingserver.xml" to "/etc/streaming/streamingserver.xml-sample"
	cp streamingserver.xml /etc/streaming/streamingserver.xml-sample
	
	echo;echo copying "streamingserver.xml" to "/etc/streaming/streamingserver.xml"
	cp streamingserver.xml /etc/streaming/streamingserver.xml
	chmod 600 /etc/streaming/streamingserver.xml

	echo;echo copying "streamingrelay.conf" to "/etc/streaming/streamingrelay.conf"
	cp streamingrelay.conf /etc/streaming/streamingrelay.conf
	chmod 600 /etc/streaming/streamingrelay.conf
		
	echo;echo copying "qtusers" to "/etc/streaming/qtusers"
	cp qtusers /etc/streaming/qtusers
	chmod 600 /etc/streaming/qtusers

	echo;echo copying "streamingadminserver.pem" to "/etc/streaming/streamingadminserver.pem"
	cp streamingadminserver.pem /etc/streaming/streamingadminserver.pem
	chmod 400 /etc/streaming/streamingadminserver.pem

	if [ ! -d /var/streaming ]; then
		echo creating "/var/streaming" directory
		mkdir -p /var/streaming
	fi
	
	echo copying "readme.html" to "/var/streaming/readme.html"
	cp readme.html /var/streaming/readme.html
	
	echo copying "usermanual.pdf" to "/var/streaming/usermanual.pdf"
	cp usermanual.pdf /var/streaming/usermanual.pdf
	
	
	if [ ! -d /var/streaming/logs ]; then
		echo creating "/var/streaming/logs" directory
		mkdir -p /var/streaming/logs
	fi
	
	if [ ! -d /usr/local/movies ]; then
		echo creating "/usr/local/movies" directory
		mkdir -p /usr/local/movies
	fi
	
	if [ ! -d /usr/local/playlists ]; then
		echo creating "/usr/local/playlists" directory
		mkdir -p /usr/local/playlists
		chmod 777 /usr/local/playlists
	fi
	
	echo copying "sample.mov" into "/usr/local/movies/sample.mov"
	cp -f sample.mov /usr/local/movies/
	
	echo copying "StreamingLoadTool" to "/usr/local/bin/StreamingLoadTool"
	cp StreamingLoadTool /usr/local/bin/
	
	echo copying "streamingloadtool.conf" to "/etc/streaming/streamingloadtool.conf"
	cp streamingloadtool.conf /etc/streaming/
	
	#WebAdmin install
	echo copying "streamingadminserver.pl" into "/usr/local/sbin/streamingadminserver.pl"
	cp -f streamingadminserver.pl /usr/local/sbin/streamingadminserver.pl
	
	if [ -d /var/streaming/AdminHtml/ ]; then
	    echo removing old version of html from "/var/streaming/AdminHtml"
	    rm -r -f /var/streaming/AdminHtml/*
	fi    
	if [ ! -d /var/streaming/ ]; then
		echo creating "/var/streaming/AdminHtml" directory
		mkdir -p /var/streaming/AdminHtml
	fi
	echo copying Admin HTML to "/var/streaming/AdminHtml" directory
	cp -f -r AdminHtml /var/streaming/
	
	echo;echo "Launching streamingadminserver.pl"
	/usr/local/sbin/streamingadminserver.pl
	
	echo;echo Installation Complete

else

	echo "Unable to perform install"
	echo "You must be logged in as root to install Darwin Streaming Server";echo
	exit 1
fi
