#define dv_videosegment_t_i                      0
#define dv_videosegment_t_k                      4
#define dv_videosegment_t_bs                     8
#define dv_videosegment_t_mb                     12
#define dv_videosegment_t_isPAL                  4992
#define dv_macroblock_t_size                     996
#define dv_macroblock_t_b                        20
#define dv_macroblock_t_eob_count                992
#define dv_macroblock_t_vlc_error                988
#define dv_macroblock_t_qno                      980
#define dv_macroblock_t_sta                      984
#define dv_macroblock_t_i                        0
#define dv_macroblock_t_j                        4
#define dv_macroblock_t_k                        8
#define dv_block_t_size                          160
#define dv_block_t_coeffs                        0
#define dv_block_t_dct_mode                      128
#define dv_block_t_class_no                      132
#define dv_block_t_reorder                       136
#define dv_block_t_reorder_sentinel              140
#define dv_block_t_offset                        144
#define dv_block_t_end                           148
#define dv_block_t_eob                           152
#define dv_block_t_mark                          156
#define bitstream_t_buf                          12
#define DV_QUALITY_BEST                          5
#define DV_QUALITY_FASTEST                       0
#define DV_QUALITY_COLOR                         1
#define DV_QUALITY_AC_MASK                       6
#define DV_QUALITY_DC                            0
#define DV_QUALITY_AC_1                          2
#define DV_QUALITY_AC_2                          4
#define DV_WEIGHT_BIAS                           6
