#!/bin/sh

#This is a startup script for MacOS X.
#It should be placed in /System/Library/StartupItems/QuickTimeServer/QuickTimeServer

. /etc/rc.common

if [ "${QTSSERVER}" = "-YES-" ]; then
    ConsoleMessage "Starting QuickTime Streaming Server Admin"

    /usr/local/bin/streamingadminserver.pl
fi
