#!/usr/bin/perl

$PACKAGE_PATH = $ENV{PACKAGE_PATH};
$VOLUME=$ARGV[0];

$SYSTEM_VERSION_PLIST="$VOLUME/System/Library/CoreServices/SystemVersion.plist";

$result_code = 0;

if (-e $SYSTEM_VERSION_PLIST) {
	$result_code = 0;
}
else {
		$result_code = (1 << 5) ;
}

exit ( $result_code );
